# Change these first1
owner: Tealk # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Homepage
    url: https://rollenspiel.monster
  - name: Mastodon-Web
    url: https://rollenspiel.social/health
  - name: Mastodon-Streaming
    url: https://rollenspiel.social/api/v1/streaming/health
  - name: Mobilizon
    url: https://rollenspiel.events
  - name: Writefreely
    url: https://blog.rollenspiel.monster
  - name: Lemmy-UI
    url: https://rollenspiel.forum
  - name: Lemmy-Backend
    url: https://rollenspiel.forum/api/v3/post/list
  - name: Flohmarkt
    url: https://rollenspiel.trade
  - name: Element
    url: https://rollenspiel.chat
  - name: Cinny
    url: https://cinny.rollenspiel.chat
  - name: Phanpy
    url: https://phanpy.rollenspiel.social
  - name: Photon
    url: https://photon.rollenspiel.forum
  - name: Authentik
    url: https://auth.rollenspiel.monster
  - name: Teamspeak
    url: 162.55.131.56
  - name: Mumble
    url: mumble.rollenspiel.monster
  - name: Synapse
    url: https://rollenspiel.chat/health
  - name: Nextcloud
    url: https://rollenspiel.cloud
  - name: Framadate
    url: https://poll.rollenspiel.monster
  - name: Bookstack
    url: https://rollenspiel.wiki
  - name: FreshRSS
    url: https://rss.rollenspiel.monster
  - name: Wallabag
    url: https://wallabag.rollenspiel.monster
  - name: Linkwarden
    url: https://linkwarden.rollenspiel.monster
  - name: PrivateBin
    url: https://paste.rollenspiel.monster
  - name: Vaultwarden
    url: https://safe.rollenspiel.monster
  - name: ntfy
    url: https://ntfy.rollenspiel.monster/v1/health
  - name: Firefly III
    url: https://firefly.rollenspiel.monster
  - name: Vikunja
    url: https://tasks.rollenspiel.monster
  - name: Grafana
    url: https://monitor.rollenspiel.monster
  - name: MollySocket
    url: https://mollysocket.rollenspiel.monster
  - name: osTicket
    url: https://ticket.rollenspiel.monster
  - name: LibreTranslate
    url: https://translate.rollenspiel.monster
  - name: Mailcow
    url: https://mail.rollenspiel.network
  - name: relay
    url: https://relay.rollenspiel.monster
  - name: PVE
    url: https://proxmox.rollenspiel.network:8006
  - name: PBS
    url: https://backup.rollenspiel.network

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
